
// USE  THIS FILE ONLY FOR PRODUCTION
// This file is part of the DoTheWorld project.
// Do not edit this file, it is automatically generated.
// See the README.md file for more information.
/*
MIT License

Copyright (c) 2023 Mateus Moutinho Queiroz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/




#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>



#ifdef __linux__
  #include <dirent.h>
  #include <unistd.h>
#elif _WIN32
  #include <windows.h>
  #include <tchar.h>
  #include <wchar.h>
  #include <locale.h>
  #include <direct.h>
#endif

struct DtwStringArray {
  int size;         

  char **strings;       
  void (*set_value)(struct DtwStringArray *self,int index,const char *value);
  void (*add_string)(struct DtwStringArray *self,const char *string);
  void (*merge_string_array)(struct DtwStringArray *self, struct DtwStringArray *other);
  void (*represent)(struct DtwStringArray *self);
  void (*free_string_array)(struct DtwStringArray *self);
  int (*find_position)(struct DtwStringArray *self,const char *string);
}; // End the structure with a semicolon
int  private_dtw_find_position(struct DtwStringArray *self,const char *string);
void private_dtw_add_string(struct DtwStringArray *self,const char *string);
void private_dtw_merge_string_array(struct DtwStringArray *self, struct DtwStringArray *other);
void private_dtw_represent_string_array(struct DtwStringArray *self);
void private_dtw_free_string_array(struct DtwStringArray *self);
void private_dtw_set_value(struct DtwStringArray *self,int index,const char *value);

struct DtwStringArray * dtw_constructor_string_array();
#ifndef SHA_256_H
#define SHA_256_H

#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
 * @brief Size of the SHA-256 sum. This times eight is 256 bits.
 */
#define SIZE_OF_SHA_256_HASH 32

/*
 * @brief Size of the chunks used for the calculations.
 *
 * @note This should mostly be ignored by the user, although when using the streaming API, it has an impact for
 * performance. Add chunks whose size is a multiple of this, and you will avoid a lot of superfluous copying in RAM!
 */
#define SIZE_OF_SHA_256_CHUNK 64

/*
 * @brief The opaque SHA-256 type, that should be instantiated when using the streaming API.
 *
 * @note Although the details are exposed here, in order to make instantiation easy, you should refrain from directly
 * accessing the fields, as they may change in the future.
 */
struct Sha_256 {
	uint8_t *hash;
	uint8_t chunk[SIZE_OF_SHA_256_CHUNK];
	uint8_t *chunk_pos;
	size_t space_left;
	size_t total_len;
	uint32_t h[8];
};

/*
 * @brief The simple SHA-256 calculation function.
 * @param hash Hash array, where the result is delivered.
 * @param input Pointer to the data the hash shall be calculated on.
 * @param len Length of the input data, in byte.
 *
 * @note If all of the data you are calculating the hash value on is available in a contiguous buffer in memory, this is
 * the function you should use.
 *
 * @note If either of the passed pointers is NULL, the results are unpredictable.
 */
void calc_sha_256(uint8_t hash[SIZE_OF_SHA_256_HASH], const void *input, size_t len);

/*
 * @brief Initialize a SHA-256 streaming calculation.
 * @param sha_256 A pointer to a SHA-256 structure.
 * @param hash Hash array, where the result will be delivered.
 *
 * @note If all of the data you are calculating the hash value on is not available in a contiguous buffer in memory, this is
 * where you should start. Instantiate a SHA-256 structure, for instance by simply declaring it locally, make your hash
 * buffer available, and invoke this function. Once a SHA-256 hash has been calculated (see further below) a SHA-256
 * structure can be initialized again for the next calculation.
 *
 * @note If either of the passed pointers is NULL, the results are unpredictable.
 */

char * calc_sha_256_returning_string(const void *input, size_t len);
/*
	@param input: the string to be hashed
	@param len: the length of the string
	@return: the hash of the string
	@note: if the input string is NULL, the results are unpredictable
*/

void calc_sha_256_from_string(uint8_t hash[SIZE_OF_SHA_256_HASH], const char *input);
/*
	@param hash: the hash array, where the result is delivered
	@param input: the string to be hashed
	@note: if the input string is NULL, the results are unpredictable
*/

int calc_sha_256_from_file(uint8_t hash[SIZE_OF_SHA_256_HASH], const char *filename);
/*
	@param hash: the hash array, where the result is delivered
	@param filename: the name of the file to be hashed
	@return: 0 if the file was hashed successfully, -1 otherwise
*/

char * calc_sha_256_from_file_returning_string(const char *filename);
/*
	@param filename: the name of the file to be hashed
	@return: the hash of the file
	@note: if the filename is NULL, the return value is NULL
*/

void sha_256_init(struct Sha_256 *sha_256, uint8_t hash[SIZE_OF_SHA_256_HASH]);

/*
 * @brief Stream more input data for an on-going SHA-256 calculation.
 * @param sha_256 A pointer to a previously initialized SHA-256 structure.
 * @param data Pointer to the data to be added to the calculation.
 * @param len Length of the data to add, in byte.
 *
 * @note This function may be invoked an arbitrary number of times between initialization and closing, but the maximum
 * data length is limited by the SHA-256 algorithm: the total number of bits (i.e. the total number of bytes times
 * eight) must be representable by a 64-bit unsigned integer. While that is not a practical limitation, the results are
 * unpredictable if that limit is exceeded.
 *
 * @note This function may be invoked on empty data (zero length), although that obviously will not add any data.
 *
 * @note If either of the passed pointers is NULL, the results are unpredictable.
 */
void sha_256_write(struct Sha_256 *sha_256, const void *data, size_t len);

/*
 * @brief Conclude a SHA-256 streaming calculation, making the hash value available.
 * @param sha_256 A pointer to a previously initialized SHA-256 structure.
 * @return Pointer to the hash array, where the result is delivered.
 *
 * @note After this function has been invoked, the result is available in the hash buffer that initially was provided. A
 * pointer to the hash value is returned for convenience, but you should feel free to ignore it: it is simply a pointer
 * to the first byte of your initially provided hash array.
 *
 * @note If the passed pointer is NULL, the results are unpredictable.
 *
 * @note Invoking this function for a calculation with no data (the writing function has never been invoked, or it only
 * has been invoked with empty data) is legal. It will calculate the SHA-256 value of the empty string.
 */
uint8_t *sha_256_close(struct Sha_256 *sha_256);



#ifdef __cplusplus
}
#endif

#endif
const char base64_table[] = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";


char *dtw_base64_encode(unsigned char *data, size_t input_length);


unsigned char *dtw_base64_decode(char *data, size_t input_length, size_t *output_length);


char *dtw_convert_binary_file_to_base64(const char *path);



char * dtw_generate_sha_from_file(const char *path);
char * dtw_generate_sha_from_string(const char *string);
long int dtw_get_file_last_motification_in_unix(const char *path);
char * dtw_convert_unix_time_to_string(long int unix_time);
char * dtw_get_file_last_motification_in_string(const char *path);
const char * private_dtw_convert_action_to_string(short action);
short private_dtw_convert_string_to_action(const char *action);
void private_dtw_add_end_bar_to_dirs_string_array(struct DtwStringArray * dirs);
char *dtw_concat_path(const char *path1, const char *path2);

bool dtw_starts_with(const char *string, const char *prefix);
bool dtw_ends_with(const char *string, const char *suffix);
char *private_dtw_replace_string_once(const char *target, const char *old_element, const char *new_element);
char* dtw_replace_string(const char *target, const char *old_element, const char *new_element);
char *private_dtw_change_beginning_of_string(const char *target,int start_element_to_remove_size, const char *new_element);

#define DTW_FILE_TYPE 1
#define DTW_FOLDER_TYPE 2
#define DTW_ALL_TYPE 3
#define DTW_NOT_FOUND -1
#define DTW_MERGE true 
#define DTW_NOT_MERGE false
#ifdef __linux__
#define dtw_create_dir(path) mkdir(path,0777)
#elif _WIN32
#define dtw_create_dir(path) _mkdir(path)
#endif

void dtw_create_dir_recursively(const char *path);

void dtw_remove_any(const char* path);

char *dtw_get_current_dir();


unsigned char *dtw_load_any_content(const char * path,int *size,bool *is_binary);
char *dtw_load_string_file_content(const char * path);

unsigned char *dtw_load_binary_content(const char * path,int *size);


bool dtw_write_any_content(const char *path,unsigned  char *content,int size);
bool dtw_write_string_file_content(const char *path,const char *content);
int dtw_entity_type(const char *path);

#ifdef __cplusplus
    bool dtw_copy_any(const char* src_path,const  char* dest_path,bool merge=false);
#else
    bool dtw_copy_any(const char* src_path,const  char* dest_path,bool merge);
#endif 

void dtw_move_any(const char* src_path, const char* dest_path,bool merge);
#define DTW_CONCAT_PATH true
#define DTW_NOT_CONCAT_PATH false

struct DtwStringArray * dtw_list_files(const char *path, bool concat_path);
struct DtwStringArray * dtw_list_dirs(const char *path, bool concat_path);

struct DtwStringArray *  dtw_list_all(const char *path,  bool concat_path);

#ifdef __linux__

bool private_dtw_verify_if_add(const int expected_type, int d_type);
bool private_dtw_verify_if_skip(struct dirent *entry);

#endif


#ifdef _WIN32

bool private_dtw_verify_if_add(const int expected_type, WIN32_FIND_DATAA entry);
bool private_dtw_verify_if_skip(WIN32_FIND_DATAA *entry);
#endif


#ifdef __cplusplus
struct DtwStringArray * dtw_list_basic(const char *path,int expected_type,bool concat_path=false);
#else 
struct DtwStringArray * dtw_list_basic(const char *path,int expected_type,bool concat_path);
#endif 

struct DtwStringArray * dtw_list_dirs_recursively(const char *path);



struct DtwStringArray *  dtw_list_files_recursively(const char *path);


struct DtwStringArray * dtw_list_all_recursively(const char *path);

struct DtwPath {
    char *original_path;
    char *dir;
    char *name;
    char *extension;
    bool dir_exists;
    bool name_exists;
    bool extension_exists;
    //Getters
    bool  (*changed)(struct DtwPath *self);
    char *(*get_full_name) (struct DtwPath *self);
    char *(*get_name) (struct DtwPath *self);
    char *(*get_extension) (struct DtwPath *self);

    char *(*get_path) (struct DtwPath *self);
    char *(*get_dir) (struct DtwPath *self);

    
    //Setters
    void (*set_extension) (struct DtwPath *self, const char *extension);
    void (*set_name) (struct DtwPath *self, const char *name);
    void (*set_dir) (struct DtwPath *self, const char *path);
    void (*set_full_name) (struct DtwPath *self, const char *full_name);
    void (*set_path) (struct DtwPath *self, const char *target_path);
    
    void (*add_start_dir)(struct DtwPath *self, const char *start_dir);
    void (*add_end_dir)(struct DtwPath *self, const char *end_dir);

    void (*represent)(struct DtwPath *self);
    void (*free_path) (struct DtwPath *self);


};
struct DtwPath * dtw_constructor_path( const char *path);
bool  private_dtw_path_changed(struct DtwPath *self);
char *private_dtw_get_full_name(struct DtwPath *self);
char *private_dtw_get_name(struct DtwPath *self);
char *private_dtw_get_extension(struct DtwPath *self);
char *private_dtw_get_path(struct DtwPath *self);
char *private_dtw_get_dir(struct DtwPath *self);

void private_dtw_set_extension(struct DtwPath *self, const char *extension);
void private_dtw_set_name(struct DtwPath * self, const char * name);
void private_dtw_set_dir(struct DtwPath *self, const char *path);

void private_dtw_set_full_name(struct DtwPath * self, const char * full_name);
void private_dtw_set_path(struct DtwPath *self, const char *target_path);

void private_dtw_add_start_dir(struct DtwPath *self, const char *start_dir);
void private_dtw_add_end_dir(struct DtwPath *self, const char *end_dir);

void private_dtw_represent_path(struct DtwPath *self);
void private_dtw_destructor_path(struct DtwPath *self);




#define DTW_LOAD_CONTENT  true
#define DTW_NOT_LOAD_CONTENT  false 
#define DTW_NOT_PRESERVE_CONTENT  false
#define DTW_PRESERVE_CONTENT  true

#define DTW_IS_BINARY true
#define DTW_IS_NOT_BINARY false
#define DTW_IGNORE true
#define DTW_NOT_IGNORE false

#define DTW_SET_AS_ACTION true
#define DTW_EXECUTE_NOW false

#define DTW_MODIFY 1
#define DTW_WRITE 2
#define DTW_REMOVE 3

struct DtwTreePart{
    
    struct DtwPath *path;
    bool content_exist_in_memory;
    size_t  hardware_content_size; 
    long last_modification_time;
    bool content_exist_in_hardware;
    bool ignore;
    bool is_binary;
    char *hawdware_content_sha;
    unsigned char *content;
    int pending_action;

    size_t content_size;
    char *(*get_content_string_by_reference)(struct DtwTreePart *self);
    unsigned char *(*get_content_binary_by_reference)(struct DtwTreePart *self);

    char *(*get_content_sha)(struct DtwTreePart *self);
    char *(*last_modification_time_in_string)(struct DtwTreePart *self);
    void (*set_any_content)(struct DtwTreePart *self,unsigned char *content,int content_size,bool is_binary);
    void (*set_string_content)(struct DtwTreePart *self,const char *content);
    void (*set_binary_content)(struct DtwTreePart *self,unsigned char *content,int content_size);
    void (*load_content_from_hardware)(struct DtwTreePart *self);
    void (*free_content)(struct DtwTreePart *self);
    void(*represent)(struct DtwTreePart *self);
    
    bool(*hardware_remove)(struct DtwTreePart *self,bool set_as_action);
    bool(*hardware_write)(struct DtwTreePart *self,bool set_as_action);
    bool(*hardware_modify)(struct DtwTreePart *self,bool set_as_action);
    bool(*hardware_commit)(struct DtwTreePart *self);


    void (*free_tree_part)(struct DtwTreePart *self);
    struct DtwTreePart *(*copy_tree_part)(struct DtwTreePart *self);
};

char *private_dtw_get_content_string_by_reference(struct DtwTreePart *self);
unsigned char *private_dtw_get_content_binary_by_reference(struct DtwTreePart *self);
char *private_dtw_get_content_sha(struct DtwTreePart *self);
char *private_dtw_last_modification_time_in_string(struct DtwTreePart *self);
void private_dtw_set_any_content(struct DtwTreePart *self,unsigned char *content,int content_size,bool is_binary);
void private_dtw_set_string_content(struct DtwTreePart *self,const char *content);
void private_dtw_set_binary_content(struct DtwTreePart *self,unsigned char *content,int content_size);
void private_dtw_load_content_from_hardware(struct DtwTreePart *self);
void private_dtw_free_content(struct DtwTreePart *self);
void private_dtw_represent_tree_part(struct DtwTreePart *self);
#ifdef __cplusplus
bool private_dtw_hardware_remove(struct DtwTreePart *self,bool set_as_action=true);
bool private_dtw_hardware_write(struct DtwTreePart *self,bool set_as_action=true);
bool private_dtw_hardware_modify(struct DtwTreePart *self,bool set_as_action=true);
#else
bool private_dtw_hardware_remove(struct DtwTreePart *self,bool set_as_action);
bool private_dtw_hardware_write(struct DtwTreePart *self,bool set_as_action);
bool private_dtw_hardware_modify(struct DtwTreePart *self,bool set_as_action);
#endif

bool private_dtw_hardware_commit(struct DtwTreePart *self);

void private_dtw_tree_part_destructor(struct DtwTreePart *self);
struct DtwTreePart * private_dtw_copy_tree(struct DtwTreePart *self);

struct DtwTreePart * dtw_tree_part_constructor(const char *path,bool load_content,bool preserve_content);

#define DTW_NOT_MINIFY  false
#define DTW_MINIFY  true
#define DTW_NOT_PRESERVE_PATH_ATRIBUTES  false
#define DTW_PRESERVE_PATH_ATRIBUTES  true
#define DTW_NOT_PRESERVE_HARDWARE_DATA  false
#define DTW_PRESERVE_HARDWARE_DATA  true
#define DTW_NOT_PRESERVE_CONTENT_DATA  false
#define DTW_PRESERVE_CONTENT_DATA  true
#define DTW_COPY_CONTENT  true 
#define DTW_PASS_BY_REFERENCE  false
#define DTW_CONSIDER_IGNORE  true
#define DTW_NOT_CONSIDER_IGNORE  false
#define DTW_PRESERVE_PATH_START true
#define DTW_NOT_PRESERVE_PATH_START false


struct  DtwTree{
    int size;
    struct DtwTreePart **tree_parts;
    void (*add_tree_part_by_copy)(
        struct DtwTree *self,
         struct DtwTreePart *tree_part
    );
    void (*add_tree_part_by_reference)(
        struct DtwTree *self,
        struct DtwTreePart *tree_part
    );
    void (*add_tree_parts_from_string_array)(
        struct DtwTree *self,
        struct DtwStringArray *paths,
        bool load_content,
        bool preserve_content
    );
    
    struct DtwTree *(*get_sub_tree)(
        struct DtwTree *self,
        const char *path,
        bool copy_content
    );

    void (*add_tree_from_hardware)(
        struct DtwTree *self,
        const char *path,
        bool load_content,
        bool preserve_content,
        bool preserve_path_start
    );
    //Listage Functions

    struct DtwTreePart *(*find_part_by_function)(
            struct DtwTree *self,
            bool (*caller)(struct  DtwTreePart *part)
                    );

    struct DtwTree *(*filter)(
            struct DtwTree *self,
            bool (*caller)(struct  DtwTreePart *part)
    );

    struct DtwTree *(*map)(
            struct DtwTree *self,
            struct  DtwTreePart*(*caller)(struct  DtwTreePart *part)
    );

    struct DtwTreePart *(*find_part_by_name)( struct DtwTree *self,const char *name);
    struct DtwTreePart *(*find_part_by_path)(   struct DtwTree *self,const char *path);


    struct DtwTransactionReport * (*report)(struct DtwTree *self);    
    //
    void (*free_tree)(struct DtwTree *self);
    void (*represent)(struct DtwTree *self);
    void (*insecure_hardware_remove_tree)(struct DtwTree *self);
    void (*insecure_hardware_write_tree)(struct DtwTree *self);
    void (*hardware_commit_tree)(struct DtwTree *self);
};

#ifdef __cplusplus
struct DtwTree *private_dtw_get_sub_tree(
    struct DtwTree *self,
    const char *path,
    bool copy_content=false
);
#else 
struct DtwTree *private_dtw_get_sub_tree(
    struct DtwTree *self,
    const char *path,
    bool copy_content
);
#endif

struct DtwTreePart *private_dtw_find_by_function(
        struct DtwTree *self,
        bool (*caller)(struct  DtwTreePart *part)
        );

struct DtwTree *private_dtw_map(
        struct DtwTree *self,
        struct  DtwTreePart* (*caller)(struct  DtwTreePart *part)
);

struct DtwTree *private_dtw_filter(
        struct DtwTree *self,
        bool (*caller)(struct  DtwTreePart *part)
);


struct DtwTreePart *private_dtw_find_tree_part_by_name(struct DtwTree *self,const char *name);
struct DtwTreePart *private_dtw_find_tree_part_by_path(struct DtwTree *self,const char *path);

void private_dtw_add_tree_part_copy(struct DtwTree *self, struct DtwTreePart *tree_part);
void private_dtw_add_tree_part_reference(struct DtwTree *self, struct DtwTreePart *tree_part);
void private_dtw_free_tree(struct DtwTree *self);
void private_dtw_represent_tree(struct DtwTree *self);
void private_dtw_add_tree_parts_from_string_array(
    struct DtwTree *self,
    struct DtwStringArray *paths,
    bool load_content,
    bool preserve_content
);
void private_dtw_add_tree_from_hardware(
    struct DtwTree *self,
    const char *path,
    bool load_content,
    bool preserve_content,
    bool preserve_path_start
);

struct DtwTransactionReport * private_dtw_create_report(struct DtwTree *self);


void private_insecure_dtw_hardware_remove_tree(struct DtwTree *self);
void private_insecure_dtw_hardware_write_tree(struct DtwTree *self);
void private_dtw_hardware_commit_tree(struct DtwTree *self);

//
struct  DtwTree * dtw_tree_constructor();



#define TOTAL_LEN_LEN 8

/*
 * Comments from pseudo-code at https://en.wikipedia.org/wiki/SHA-2 are reproduced here.
 * When useful for clarification, portions of the pseudo-code are reproduced here too.
 */

/*
 * @brief Rotate a 32-bit value by a number of bits to the right.
 * @param value The value to be rotated.
 * @param count The number of bits to rotate by.
 * @return The rotated value.
 */
static inline uint32_t right_rot(uint32_t value, unsigned int count)
{
	/*
	 * Defined behaviour in standard C for all count where 0 < count < 32, which is what we need here.
	 */
	return value >> count | value << (32 - count);
}

/*
 * @brief Update a hash value under calculation with a new chunk of data.
 * @param h Pointer to the first hash item, of a total of eight.
 * @param p Pointer to the chunk data, which has a standard length.
 *
 * @note This is the SHA-256 work horse.
 */
static inline void consume_chunk(uint32_t *h, const uint8_t *p)
{
	unsigned i, j;
	uint32_t ah[8];

	/* Initialize working variables to current hash value: */
	for (i = 0; i < 8; i++)
		ah[i] = h[i];

	/*
	 * The w-array is really w[64], but since we only need 16 of them at a time, we save stack by
	 * calculating 16 at a time.
	 *
	 * This optimization was not there initially and the rest of the comments about w[64] are kept in their
	 * initial state.
	 */

	/*
	 * create a 64-entry message schedule array w[0..63] of 32-bit words (The initial values in w[0..63]
	 * don't matter, so many implementations zero them here) copy chunk into first 16 words w[0..15] of the
	 * message schedule array
	 */
	uint32_t w[16];

	/* Compression function main loop: */
	for (i = 0; i < 4; i++) {
		for (j = 0; j < 16; j++) {
			if (i == 0) {
				w[j] =
				    (uint32_t)p[0] << 24 | (uint32_t)p[1] << 16 | (uint32_t)p[2] << 8 | (uint32_t)p[3];
				p += 4;
			} else {
				/* Extend the first 16 words into the remaining 48 words w[16..63] of the
				 * message schedule array: */
				const uint32_t s0 = right_rot(w[(j + 1) & 0xf], 7) ^ right_rot(w[(j + 1) & 0xf], 18) ^
						    (w[(j + 1) & 0xf] >> 3);
				const uint32_t s1 = right_rot(w[(j + 14) & 0xf], 17) ^
						    right_rot(w[(j + 14) & 0xf], 19) ^ (w[(j + 14) & 0xf] >> 10);
				w[j] = w[j] + s0 + w[(j + 9) & 0xf] + s1;
			}
			const uint32_t s1 = right_rot(ah[4], 6) ^ right_rot(ah[4], 11) ^ right_rot(ah[4], 25);
			const uint32_t ch = (ah[4] & ah[5]) ^ (~ah[4] & ah[6]);

			/*
			 * Initialize array of round constants:
			 * (first 32 bits of the fractional parts of the cube roots of the first 64 primes 2..311):
			 */
			static const uint32_t k[] = {
			    0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1, 0x923f82a4,
			    0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3, 0x72be5d74, 0x80deb1fe,
			    0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786, 0x0fc19dc6, 0x240ca1cc, 0x2de92c6f,
			    0x4a7484aa, 0x5cb0a9dc, 0x76f988da, 0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7,
			    0xc6e00bf3, 0xd5a79147, 0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc,
			    0x53380d13, 0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
			    0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070, 0x19a4c116,
			    0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a, 0x5b9cca4f, 0x682e6ff3,
			    0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208, 0x90befffa, 0xa4506ceb, 0xbef9a3f7,
			    0xc67178f2};

			const uint32_t temp1 = ah[7] + s1 + ch + k[i << 4 | j] + w[j];
			const uint32_t s0 = right_rot(ah[0], 2) ^ right_rot(ah[0], 13) ^ right_rot(ah[0], 22);
			const uint32_t maj = (ah[0] & ah[1]) ^ (ah[0] & ah[2]) ^ (ah[1] & ah[2]);
			const uint32_t temp2 = s0 + maj;

			ah[7] = ah[6];
			ah[6] = ah[5];
			ah[5] = ah[4];
			ah[4] = ah[3] + temp1;
			ah[3] = ah[2];
			ah[2] = ah[1];
			ah[1] = ah[0];
			ah[0] = temp1 + temp2;
		}
	}

	/* Add the compressed chunk to the current hash value: */
	for (i = 0; i < 8; i++)
		h[i] += ah[i];
}

/*
 * Public functions. See header file for documentation.
 */

void sha_256_init(struct Sha_256 *sha_256, uint8_t hash[SIZE_OF_SHA_256_HASH])
{
	sha_256->hash = hash;
	sha_256->chunk_pos = sha_256->chunk;
	sha_256->space_left = SIZE_OF_SHA_256_CHUNK;
	sha_256->total_len = 0;
	/*
	 * Initialize hash values (first 32 bits of the fractional parts of the square roots of the first 8 primes
	 * 2..19):
	 */
	sha_256->h[0] = 0x6a09e667;
	sha_256->h[1] = 0xbb67ae85;
	sha_256->h[2] = 0x3c6ef372;
	sha_256->h[3] = 0xa54ff53a;
	sha_256->h[4] = 0x510e527f;
	sha_256->h[5] = 0x9b05688c;
	sha_256->h[6] = 0x1f83d9ab;
	sha_256->h[7] = 0x5be0cd19;
}

void sha_256_write(struct Sha_256 *sha_256, const void *data, size_t len)
{
	sha_256->total_len += len;

	
	const uint8_t *p = (const uint8_t *)data;


	while (len > 0) {
		/*
		 * If the input chunks have sizes that are multiples of the calculation chunk size, no copies are
		 * necessary. We operate directly on the input data instead.
		 */
		if (sha_256->space_left == SIZE_OF_SHA_256_CHUNK && len >= SIZE_OF_SHA_256_CHUNK) {
			consume_chunk(sha_256->h, p);
			len -= SIZE_OF_SHA_256_CHUNK;
			p += SIZE_OF_SHA_256_CHUNK;
			continue;
		}
		/* General case, no particular optimization. */
		const size_t consumed_len = len < sha_256->space_left ? len : sha_256->space_left;
		memcpy(sha_256->chunk_pos, p, consumed_len);
		sha_256->space_left -= consumed_len;
		len -= consumed_len;
		p += consumed_len;
		if (sha_256->space_left == 0) {
			consume_chunk(sha_256->h, sha_256->chunk);
			sha_256->chunk_pos = sha_256->chunk;
			sha_256->space_left = SIZE_OF_SHA_256_CHUNK;
		} else {
			sha_256->chunk_pos += consumed_len;
		}
	}
}

uint8_t *sha_256_close(struct Sha_256 *sha_256)
{
	uint8_t *pos = sha_256->chunk_pos;
	size_t space_left = sha_256->space_left;
	uint32_t *const h = sha_256->h;

	/*
	 * The current chunk cannot be full. Otherwise, it would already have be consumed. I.e. there is space left for
	 * at least one byte. The next step in the calculation is to add a single one-bit to the data.
	 */
	*pos++ = 0x80;
	--space_left;

	/*
	 * Now, the last step is to add the total data length at the end of the last chunk, and zero padding before
	 * that. But we do not necessarily have enough space left. If not, we pad the current chunk with zeroes, and add
	 * an extra chunk at the end.
	 */
	if (space_left < TOTAL_LEN_LEN) {
		memset(pos, 0x00, space_left);
		consume_chunk(h, sha_256->chunk);
		pos = sha_256->chunk;
		space_left = SIZE_OF_SHA_256_CHUNK;
	}
	const size_t left = space_left - TOTAL_LEN_LEN;
	memset(pos, 0x00, left);
	pos += left;
	size_t len = sha_256->total_len;
	pos[7] = (uint8_t)(len << 3);
	len >>= 5;
	int i;
	for (i = 6; i >= 0; --i) {
		pos[i] = (uint8_t)len;
		len >>= 8;
	}
	consume_chunk(h, sha_256->chunk);
	/* Produce the final hash value (big-endian): */
	int j;
	uint8_t *const hash = sha_256->hash;
	for (i = 0, j = 0; i < 8; i++) {
		hash[j++] = (uint8_t)(h[i] >> 24);
		hash[j++] = (uint8_t)(h[i] >> 16);
		hash[j++] = (uint8_t)(h[i] >> 8);
		hash[j++] = (uint8_t)h[i];
	}
	return sha_256->hash;
}

char * sha256_open_file(const char *filename, int *size){
	FILE *file = fopen(filename, "rb");
	if (file == NULL) {
		return NULL;
	}
	fseek(file,0,SEEK_END);
    *size = ftell(file);
    fseek(file,0,SEEK_SET);
    char *content = (char*)malloc(*size +1);
    fread(content,1,*size,file);
	fclose(file);
	return content;
}

//Wrapper functions
void calc_sha_256(uint8_t hash[SIZE_OF_SHA_256_HASH], const void *input, size_t len)
{
	struct Sha_256 sha_256;
	sha_256_init(&sha_256, hash);
	sha_256_write(&sha_256, input, len);
	(void)sha_256_close(&sha_256);
}

char * calc_sha_256_returning_string(const void *input, size_t len)
{
	uint8_t hash[SIZE_OF_SHA_256_HASH];
	calc_sha_256(hash, input, len);
	char *hash_string = (char*)malloc(SIZE_OF_SHA_256_HASH * 2 + 1);
	for (unsigned int i = 0; i < SIZE_OF_SHA_256_HASH; i++) {
		sprintf(hash_string + i * 2, "%02x", hash[i]);
	}
	return hash_string;
}

void  calc_sha_256_from_string(uint8_t hash[SIZE_OF_SHA_256_HASH], const char *input)
{
	calc_sha_256(hash, input, strlen(input));
	
}

char * calc_sha_256_from_string_returning_string(const char *input)
{
	return calc_sha_256_returning_string(input, strlen(input));
}

int calc_sha_256_from_file(uint8_t hash[SIZE_OF_SHA_256_HASH], const char *filename)
{
	int size;
	char *content = sha256_open_file(filename, &size);
	if(content == NULL){
		return -1;
	}
	calc_sha_256(hash, content, size);
	free(content);
	return 0;
}

char * calc_sha_256_from_file_returning_string(const char *filename)
{
	int size;
	char *content = sha256_open_file(filename, &size);
	if(content == NULL){
		return NULL;
	}
	char *hash_string = calc_sha_256_returning_string(content, size);
	free(content);
	return hash_string;

}



char *dtw_base64_encode(unsigned char *data, size_t input_length){
    size_t output_length = 4 * ((input_length + 2) / 3);

    char *encoded_data = (char *)malloc(output_length + 1);

    if (encoded_data == NULL) return NULL;

    size_t i, j;
    for (i = 0, j = 0; i < input_length; ) {
        unsigned char b0 = i < input_length ? data[i++] : 0;
        unsigned char b1 = i < input_length ? data[i++] : 0;
        unsigned char b2 = i < input_length ? data[i++] : 0;

        unsigned char b = b0 >> 2;
        encoded_data[j++] = base64_table[b];

        b = (b0 << 4) & 0x3F;
        b |= b1 >> 4;
        encoded_data[j++] = base64_table[b];

        b = (b1 << 2) & 0x3F;
        b |= b2 >> 6;
        encoded_data[j++] = i <= input_length + 1 ? base64_table[b] : '=';

        b = b2 & 0x3F;
        encoded_data[j++] = i <= input_length ? base64_table[b] : '=';
    }

    encoded_data[j] = '\0';
    return encoded_data;
}


unsigned char *dtw_base64_decode(char *data, size_t input_length, size_t *output_length){
    if (input_length % 4 != 0) return NULL;

    *output_length = input_length / 4 * 3;
    if (data[input_length - 1] == '=') (*output_length)--;
    if (data[input_length - 2] == '=') (*output_length)--;

    unsigned char *decoded_data = (unsigned char*) malloc(*output_length);
    if (decoded_data == NULL) return NULL;

    size_t i, j;
    for (i = 0, j = 0; i < input_length; ) {
        unsigned char b0 = data[i] == '=' ? 0 & i++ : strchr(base64_table, data[i++]) - base64_table;
        unsigned char b1 = data[i] == '=' ? 0 & i++ : strchr(base64_table, data[i++]) - base64_table;
        unsigned char b2 = data[i] == '=' ? 0 & i++ : strchr(base64_table, data[i++]) - base64_table;
        unsigned char b3 = data[i] == '=' ? 0 & i++ : strchr(base64_table, data[i++]) - base64_table;

        unsigned char b = (b0 << 2) | (b1 >> 4);
        decoded_data[j++] = b;

        if (j < *output_length) {
            b = (b1 << 4) | (b2 >> 2);
            decoded_data[j++] = b;
        }
        if (j < *output_length) {
            b = (b2 << 6) | b3;
            decoded_data[j++] = b;
        }
    }

    return decoded_data;
}

char *dtw_convert_binary_file_to_base64(const char *path){
     int size;
     unsigned char *data  = dtw_load_binary_content(path, &size);
    char *b64   = dtw_base64_encode(data, size);
    free(data);
    return b64;
}

char * dtw_generate_sha_from_file(const char *path){
    return calc_sha_256_from_file_returning_string(path);
}


char * dtw_generate_sha_from_string(const char *string){
    return calc_sha_256_from_string_returning_string(string);
}


long int dtw_get_file_last_motification_in_unix(const char *path){
    struct stat attr;
    stat(path, &attr);
    // convert to unix time
    time_t last_modification_in_unix = attr.st_mtime;
    return last_modification_in_unix;
}

char * dtw_convert_unix_time_to_string(long int unix_time){
    struct tm * timeinfo;
    #ifdef _WIN32
        //get timeinfo from windows
        time_t rawtime = unix_time;
        timeinfo = localtime(&rawtime);
    #else
        timeinfo = localtime(&unix_time);
    #endif
    char *time_string = (char *)malloc(100);
    strftime(time_string, 100, "%Y-%m-%d %H:%M:%S", timeinfo);
    return time_string;
}

char * dtw_get_file_last_motification_in_string(const char *path){
    long int last_modification_in_unix = dtw_get_file_last_motification_in_unix(path);
    char *last_modification_in_string = dtw_convert_unix_time_to_string(last_modification_in_unix);
    return last_modification_in_string;
}

const char * private_dtw_convert_action_to_string(short action){
    switch (action){
        case DTW_REMOVE:
            return "remove";
        case DTW_WRITE:
            return "write";
        case DTW_MODIFY:
            return "modify";
    }
    return NULL;
}

short private_dtw_convert_string_to_action(const char *action){
    if(strcmp(action,"remove") == 0){
        return DTW_REMOVE;
    }
    if(strcmp(action,"write") == 0){
        return DTW_WRITE;
    }
    if(strcmp(action,"modify") == 0){
        return DTW_MODIFY;
    }
    return -1;
}

void private_dtw_add_end_bar_to_dirs_string_array(struct DtwStringArray * dirs){
    for(int i = 0; i < dirs->size; i++){
  
        if(!dtw_ends_with(dirs->strings[i], "/") || !dtw_ends_with(dirs->strings[i],"\\")){
            char *formated_dir =  (char*)malloc(strlen(dirs->strings[i]) + 3);
            sprintf(formated_dir,"%s/",dirs->strings[i]);
            dirs->set_value(dirs,i,formated_dir);
            free(formated_dir);
        }    
            
         
    }
}

char *dtw_concat_path(const char *path1, const char *path2){
    char *path = (char *)malloc(strlen(path1) + strlen(path2) + 3);

        if(dtw_ends_with(path1, "/") || dtw_ends_with(path1, "\\")){
            sprintf(path,"%s%s",path1,path2);

        }
        else{
            sprintf(path,"%s/%s",path1,path2);
      
        }
   

    return path;
}



bool dtw_starts_with(const char *string, const char *prefix){
    if(strncmp(string, prefix, strlen(prefix)) == 0){
        return true;
    }
    return false;
}

bool dtw_ends_with(const char *string, const char *suffix){
    if(strlen(string) < strlen(suffix)){
        return false;
    }
    if(strcmp(string + strlen(string) - strlen(suffix), suffix) == 0){
        return true;
    }
    return false;
}

char *private_dtw_replace_string_once(const char *target, const char *old_element, const char *new_element) {

    const char *pos = strstr(target, old_element);

    int size_of_old_element = strlen(old_element);
    int size_of_new_element = strlen(new_element);
    // Allocate memory for the new string
    char *result = (char *)malloc(strlen(target) + size_of_new_element - size_of_old_element + 1);

    // Copy the part of the original string before the old substring
    strncpy(result, target, pos - target);

    // Copy the new substring to the result string
    strcpy(result + (pos - target), new_element);

    // Copy the rest of the original string after the old substring
    strcpy(result + (pos - target) + size_of_new_element, pos + size_of_old_element);

    return result;

    

}

char* dtw_replace_string(const char *target, const char *old_element, const char *new_element) {
    char *result = (char *)malloc(strlen(target) + 1);
    strcpy(result, target);
    char *temp = NULL;
    while (strstr(result, old_element) != NULL) {
        temp = private_dtw_replace_string_once(result, old_element, new_element);
        free(result);
        result = temp;
    }
    return result;
}

char *private_dtw_change_beginning_of_string(const char *target,int start_element_to_remove_size, const char *new_element) {
    int target_size = strlen(target);
    int new_element_size = strlen(new_element);
    char *result = (char *)malloc(target_size- start_element_to_remove_size + new_element_size   +2);
    strcpy(result, new_element);
    char *new_target = (char *)malloc(target_size - start_element_to_remove_size + 2);
    strcpy(new_target, target + start_element_to_remove_size);
    strcat(result, new_target);
    free(new_target);
    return result;
}




#ifdef __linux__
#define dtw_create_dir(path) mkdir(path,0777)
#elif _WIN32
#define dtw_create_dir(path) _mkdir(path)
#endif



void dtw_create_dir_recursively(const char *path){
    bool check = dtw_create_dir(path);
  
    int size_path = strlen(path);
    for(int i=0;i <  size_path;i++){
        if(path[i] == '\\'  || path[i] == '/'   && i != size_path - 1){
            
            char * current_path = (char*)malloc(i + 1);
            current_path[i] = '\0';
            strncpy(current_path,path,i);
          
            dtw_create_dir(current_path);
            free(current_path);
        }
    }


    
    dtw_create_dir(path);
}

char *dtw_get_current_dir(){
    char *path = (char*)malloc(1024);
    getcwd(path,1024);
    char*path_with_bar = (char*)malloc(strlen(path) + 2);
    sprintf(path_with_bar,"%s/",path);
    free(path);
    return path_with_bar;
}



void dtw_remove_any(const char* path) {
    //means is an file
    if(remove(path) == 0){
        return;
    }
    
    struct DtwStringArray *files = dtw_list_files_recursively(path);
    int size = files->size;
    for(int i = 0; i < size; i++){
        remove(files->strings[i]);
    }
    files->free_string_array(files);


    struct DtwStringArray *dirs = dtw_list_dirs_recursively(path);
    size = dirs->size;
    for(int i = dirs->size -1; i >=0; i--){
        rmdir(dirs->strings[i]);
    }
    dirs->free_string_array(dirs);
    //remove / to the path 
    
    
   
 
}


unsigned char *dtw_load_any_content(const char * path,int *size,bool *is_binary){
    FILE *file = fopen(path,"rb");
    if(file == NULL){
        free(file);
        return NULL;
    }
    fseek(file,0,SEEK_END);
    *size = ftell(file);
    fseek(file,0,SEEK_SET);
    unsigned char *content = (unsigned char*)malloc(*size +1);
    fread(content,1,*size,file);

    *is_binary = false;
    for(int i = 0;i < *size;i++){
        if(content[i] == 0){
            *is_binary = true;
            break;
        }
    }
    if(!*is_binary){
        content[*size] = '\0';
    }

    fclose(file);
    return content;
}


char *dtw_load_string_file_content(const char * path){
    FILE *file = fopen(path,"r");
    if(file == NULL){
        return NULL;
    }
    fseek(file,0,SEEK_END);
    int size = ftell(file);
    fseek(file,0,SEEK_SET);
    char *content = (char*)malloc(size +1);
    fread(content,1,size,file);
    content[size] = '\0';
    fclose(file);
    return content;
}


unsigned char *dtw_load_binary_content(const char * path,int *size){
    FILE *file = fopen(path,"rb");
    if(file == NULL){
        return NULL;
    }
    fseek(file,0,SEEK_END);
    *size = ftell(file);
    fseek(file,0,SEEK_SET);
    unsigned char *content = (unsigned char*)malloc(*size);
    fread(content,1,*size,file);
    fclose(file);
    return content;
}


bool dtw_write_any_content(const char *path,unsigned  char *content,int size){
    //Iterate through the path and create directories if they don't exist
    
    for(int i = strlen(path)-1;i > 0;i--){
        //runs in negative mode til / or \ is found
        if(path[i] == '\\' || path[i] == '/'){
            char *dir_path =(char*)malloc(i +2);
            dir_path[i] = '\0';
            strncpy(dir_path,path,i);
            
            dtw_create_dir_recursively(dir_path);
            free(dir_path);
        
            break;
        }
    }

    FILE *file = fopen(path,"wb");
    if(file == NULL){
   
        return false;
    }
    
    fwrite(content, sizeof(char),size, file);
    
    fclose(file);
    return true;
}


bool dtw_write_string_file_content(const char *path,const char *content){
    int size;
    if(content == NULL){
        size = 0;
    }
    else{
        size = strlen(content);
    }
    return dtw_write_any_content(path,(unsigned char*)content,size);
}

int dtw_entity_type(const char *path){
    //returns 1 for file, 2 for directory, -1 for not found
    struct stat path_stat; 

    if(stat(path,&path_stat) == 0){
        if(S_ISREG(path_stat.st_mode)){
            return DTW_FILE_TYPE;
        }else if(S_ISDIR(path_stat.st_mode)){
            return DTW_FOLDER_TYPE;
        }
    }
    return DTW_NOT_FOUND;
}

bool dtw_copy_any(const char* src_path,const  char* dest_path,bool merge) {

    //verify if is an file
    int type = dtw_entity_type(src_path);
    if(type == DTW_NOT_FOUND){
        return false;
    }

    if(type == DTW_FILE_TYPE){
    
        int size;
        bool is_binary;
        unsigned char *content = dtw_load_any_content(src_path,&size,&is_binary);
        bool result =  dtw_write_any_content(dest_path,content,size);
        free(content);
        return result;
    }
    //means is an directory

    //remove the previous directory if merge is false
    if(!merge){
        dtw_remove_any(dest_path);
    }
    //creating dirs
    struct DtwStringArray *dirs = dtw_list_dirs_recursively(src_path);
    
    int size = dirs->size;
    int src_path_size = strlen(src_path);

    for(int i = 0; i < size; i++){
        
        char *new_path_dir = private_dtw_change_beginning_of_string(dirs->strings[i],src_path_size,dest_path);
        dtw_create_dir_recursively(new_path_dir);
        free(new_path_dir);
    }
    dirs->free_string_array(dirs);
    

    struct DtwStringArray *files = dtw_list_files_recursively(src_path);
   
    for(int i = 0; i < files->size; i++){
        int file_size;
        bool is_binary;
        unsigned char *content = dtw_load_any_content(files->strings[i],&file_size,&is_binary);
        char *new_path = private_dtw_change_beginning_of_string(files->strings[i],src_path_size,dest_path);

        dtw_write_any_content(new_path,content,file_size);
        free(content);
        free(new_path);

       
    }

    files->free_string_array(files);
    
    return true;
    
}

void dtw_move_any(const char* src_path, const char* dest_path,bool merge) {
    dtw_copy_any(src_path,dest_path,merge);
    dtw_remove_any(src_path);
}


struct DtwStringArray * dtw_list_files(const char *path, bool concat_path){
    return dtw_list_basic(path,  DTW_FILE_TYPE, concat_path);
}

struct DtwStringArray * dtw_list_dirs(const char *path, bool concat_path){
    return dtw_list_basic(path,DTW_FOLDER_TYPE, concat_path);
}

struct DtwStringArray *  dtw_list_all(const char *path,  bool concat_path){
    return dtw_list_basic(path, DTW_ALL_TYPE, concat_path);
}


#ifdef __linux__

bool private_dtw_verify_if_add(const int expected_type, int d_type){
    if (expected_type == DTW_FILE_TYPE  && d_type == DT_REG) {
        return true;
    }

    if (expected_type == DTW_FOLDER_TYPE && d_type == DT_DIR) {
        return true;
    }

    if (expected_type == DTW_ALL_TYPE) {
      
        return true;
    }
    return false;
}
bool private_dtw_verify_if_skip(struct dirent *entry){
        if (strcmp(entry->d_name, ".") == 0 || strcmp(entry->d_name, "..") == 0) {
            return true;
        }
        return false;
}

struct DtwStringArray * dtw_list_basic(const char *path,int expected_type,bool concat_path){

    DIR *dir;
    struct dirent *entry;

    //array of directories
    struct DtwStringArray *dirs = dtw_constructor_string_array();
    int i = 0;

    //means that the directory is not found
    if ((dir = opendir(path)) == NULL) {
        return dirs;
    }

    //reads the directory and adds the directories to the array
    while ((entry = readdir(dir)) != NULL) {
        //means is not a directory
        if (private_dtw_verify_if_skip(entry)){
            continue;
        }
    
        if (private_dtw_verify_if_add(expected_type,entry->d_type)) {
            
            
            if(concat_path){
                //allocates memory for the directory
                char *generated_dir = (char*)malloc(strlen(path) + strlen(entry->d_name) + 2);
                if(path[strlen(path) - 1] == '/'){
                    sprintf(generated_dir, "%s%s", path, entry->d_name);
                }
                else{
                    sprintf(generated_dir, "%s/%s", path, entry->d_name);
                }

                
                
                dirs->add_string(dirs, generated_dir);
                free(generated_dir);

            }
            else{
                dirs->add_string(dirs, entry->d_name);
                
            }

            i++;
        }
    }

    if(expected_type == DTW_FOLDER_TYPE){
        private_dtw_add_end_bar_to_dirs_string_array(dirs);   
    }
    closedir(dir);

    return dirs;
}

#endif

#ifdef _WIN32


bool private_dtw_verify_if_add(const int expected_type, WIN32_FIND_DATAA entry){
    #define WIN32_FILETYPE 32

    if (expected_type == DTW_FILE_TYPE && entry.dwFileAttributes == WIN32_FILETYPE) {
        return true;
    }

    if (expected_type == DTW_FOLDER_TYPE && entry.dwFileAttributes != WIN32_FILETYPE){
        return true;
    }

    if (expected_type == DTW_ALL_TYPE) {
        return true;
    }
    
    return false;
}

bool private_dtw_verify_if_skip(WIN32_FIND_DATAA *entry){
    if (strcmp(entry->cFileName, ".") == 0 || strcmp(entry->cFileName, "..") == 0) {
        return true;
    }
    return false;
}

struct DtwStringArray *  dtw_list_basic(const char *path,int expected_type,bool concat_path){

    WIN32_FIND_DATAA file_data;
    HANDLE file_handle;
    char search_path[MAX_PATH];

    //array of directories
    struct DtwStringArray *dirs = dtw_constructor_string_array();
    int i = 0;

    // build the search path string
    snprintf(search_path, MAX_PATH, "%s\\*", path);

    // try to open the directory
    if ((file_handle = FindFirstFileA(search_path, &file_data)) == INVALID_HANDLE_VALUE) {
        return dirs;
    }

    do {
        // skip "." and ".." directories
        if (private_dtw_verify_if_skip(&file_data)){
            continue;
        }

        // verify if it's a file or directory
        if (private_dtw_verify_if_add(expected_type, file_data)) {
            
            if(concat_path){
                // allocate memory for the directory
                if(path[strlen(path) - 1] == '\\' || path[strlen(path) - 1] == '/'){
                    char *generated_dir = (char*)malloc(strlen(path) + strlen(file_data.cFileName) + 1);
                    sprintf(generated_dir, "%s%s", path, file_data.cFileName);
                    dirs->add_string(dirs, generated_dir);
                    free(generated_dir);
                }
                else{
                    char *generated_dir = (char*)malloc(strlen(path) + strlen(file_data.cFileName) + 2);
                    

                    sprintf(generated_dir, "%s/%s", path, file_data.cFileName);
                   
                    dirs->add_string(dirs, generated_dir);
                    free(generated_dir);
                }
                
    
            }
            else{
                dirs->add_string(dirs, file_data.cFileName);
            
            }

            i++;
        }
    } while (FindNextFileA(file_handle, &file_data) != 0);

        if(expected_type == DTW_FOLDER_TYPE){
            private_dtw_add_end_bar_to_dirs_string_array(dirs);   
        }
    
    FindClose(file_handle);

    return dirs;
}
#endif

struct DtwStringArray * dtw_list_dirs_recursively(const char *path){

        struct  DtwStringArray *dirs  = dtw_constructor_string_array();
        //verify if the path is a directory
    
        int entity_type = dtw_entity_type(path);
        if(entity_type != DTW_FOLDER_TYPE){
                return dirs;
        }
      
        
        dirs->add_string(dirs,path);
        private_dtw_add_end_bar_to_dirs_string_array(dirs);
        int i = 0;
        //The size of dirs will increase til it reaches the end of the array
        while(i < dirs->size){                
                struct DtwStringArray *sub_dirs = dtw_list_basic(
                    dirs->strings[i],
                    DTW_FOLDER_TYPE,
                    true
                    );
                //merge the two dirs
                dirs->merge_string_array(dirs,sub_dirs);
                sub_dirs->free_string_array(sub_dirs);
                i++;
               
        }
        //unsifth path in dirs 
        
        
      

        return dirs;
}



struct DtwStringArray *  dtw_list_files_recursively(const char *path){
    
    struct DtwStringArray *dirs = dtw_list_dirs_recursively(path);
    
    struct  DtwStringArray *files = dtw_constructor_string_array();
    
    for(int i = 0; i < dirs->size; i++){
        struct DtwStringArray *sub_files = dtw_list_basic(dirs->strings[i],DTW_FILE_TYPE,DTW_CONCAT_PATH);
        files->merge_string_array(files,sub_files);
        sub_files->free_string_array(sub_files);
    }
    dirs->free_string_array(dirs);
    return files;
}


struct DtwStringArray * dtw_list_all_recursively(const char *path){

    struct DtwStringArray *dirs = dtw_list_dirs_recursively(path);
    
    struct DtwStringArray *all = dtw_constructor_string_array();
    
    for(int i = 0; i < dirs->size; i++){

        if(!dtw_ends_with(dirs->strings[i], "/") || !dtw_ends_with(dirs->strings[i], "\\") ){
            char *formated_dir =  (char*)malloc(strlen(dirs->strings[i]) + 2);
            sprintf(formated_dir,"%s/",dirs->strings[i]);
            all->add_string(all,formated_dir);
            free(formated_dir);
        }
        else{
            all->add_string(all,dirs->strings[i]);
        }


        struct DtwStringArray *sub_files = dtw_list_basic(dirs->strings[i],DTW_FILE_TYPE,true);
        all->merge_string_array(all,sub_files);
        sub_files->free_string_array(sub_files);
    }
    dirs->free_string_array(dirs);
    return all;
}


struct DtwPath * dtw_constructor_path( const char *path) {
    struct DtwPath *self = (struct DtwPath *)malloc(sizeof(struct DtwPath));

    self->dir = (char *)malloc(0);
    self->name = (char *)malloc(0);
    self->extension = (char *)malloc(0);
    self->dir_exists = false;
    self->name_exists = false;
    self->extension_exists = false;

    self->changed = private_dtw_path_changed;
    self->get_full_name =private_dtw_get_full_name;
    self->get_name = private_dtw_get_name;
    self->get_extension = private_dtw_get_extension;


    self->get_path = private_dtw_get_path;
    self->get_dir = private_dtw_get_dir;

    self->set_extension = private_dtw_set_extension;
    self->set_name = private_dtw_set_name;
    self->set_dir = private_dtw_set_dir;
    self->set_full_name = private_dtw_set_full_name;
    self->set_path = private_dtw_set_path;
    self->add_start_dir = private_dtw_add_start_dir;
    self->add_end_dir = private_dtw_add_end_dir;
    self->represent = private_dtw_represent_path;   
    self->free_path = private_dtw_destructor_path;

    self->set_path(self, path);
    self->original_path = self->get_path(self);
    
    return self;
}
bool private_dtw_path_changed(struct DtwPath *self){
    char *path = self->get_path(self);
    if(strcmp(self->original_path,path ) == 0){
        free(path);
        return false;
    }
    free(path);
    return true;
}


char * private_dtw_get_name(struct DtwPath *self){
    if(self->name_exists == false){
        return NULL;
    }
    char *name = (char *)malloc(strlen(self->name) + 1);
    strcpy(name, self->name);

    return name;
}
char * private_dtw_get_extension(struct DtwPath *self){
    if(self->extension_exists == false){
        return NULL;
    }
    char *extension = (char *)malloc(strlen(self->extension) + 1);
    strcpy(extension, self->extension);
    return extension;
}

char * private_dtw_get_full_name(struct DtwPath *self){

    if(self->name_exists == true &&  self->extension_exists == true){
        char *full_name = (char *)malloc(strlen(self->name) + strlen(self->extension) + 2);
        sprintf(full_name, "%s.%s",self->name, self->extension);
        return full_name;
    }

    if(self->name_exists == true &&  self->extension_exists == false){
        char *full_name = (char *)malloc(strlen(self->name) + 1);
        sprintf(full_name, "%s",self->name);
        return full_name;
    }
    
    if(self->name_exists == false &&  self->extension_exists == true){
        char *full_name = (char *)malloc(strlen(self->extension) + 1);
        sprintf(full_name, "%s",self->extension);
        return full_name;
    }    
    return NULL;
}

char * private_dtw_get_dir(struct DtwPath *self){
    if(self->dir_exists == false){
        return NULL;
    }
    char *dir = (char *)malloc(strlen(self->dir) + 1);
    strcpy(dir, self->dir);
    return dir;
}

char * private_dtw_get_path(struct DtwPath *self){
    //concat the path, name and extension with / 
    char *full_name = self->get_full_name(self);
    char *dir = self->get_dir(self);

    #define FULL_NAME_EXIST full_name != NULL
    #define FULL_NAME_NOT_EXIST full_name == NULL
    #define DIR_EXIST dir != NULL
    #define DIR_NOT_EXIST dir == NULL

    if(FULL_NAME_EXIST && DIR_EXIST){
        char *path = dtw_concat_path(dir, full_name);
        free(dir);
        free(full_name);
        return path;
    }
    if(FULL_NAME_EXIST && DIR_NOT_EXIST){
        char *path = (char *)malloc(strlen(full_name) + 1);
        sprintf(path, "%s",full_name);
        free(dir);
        free(full_name);
        return path;
    }
    if(FULL_NAME_NOT_EXIST && DIR_EXIST){
        char *path = dtw_concat_path(dir, "");
        free(dir);
        free(full_name);
        return path;
    }
    free(dir);
    free(full_name);
    return NULL;
}



void private_dtw_set_extension(struct DtwPath *self, const char *extension){
    if(strcmp(extension, "") == 0){
        return;
    }
    self->extension_exists = true;
    int extension_size = strlen(extension);
    self->extension = (char *)realloc(self->extension, extension_size+2);
    strcpy(self->extension, extension);
    self->extension[extension_size] = '\0';
}


void private_dtw_set_name(struct DtwPath * self, const char * name){
    if(strcmp(name, "") == 0){
        return;
    }
    self->name_exists = true;
    int name_size = strlen(name);
    self->name = (char *)realloc(self->name, name_size +1);
   
    strcpy(self->name, name);
    self->name[name_size] = '\0';
}



void private_dtw_set_full_name(struct DtwPath * self, const char * full_name){
    self->name_exists = false;
    self->extension_exists = false;

    int full_name_size = strlen(full_name);
    for(int i = 0; i < full_name_size; i++){
        if(full_name[i] == '.'){
            int name_size = i;
            int extension_size = full_name_size - i - 1;

            char *name = (char *)malloc(name_size + 1);
            strncpy(name, full_name, name_size);
            name[name_size] = '\0';
            self->set_name(self, name);
            free(name);

            char *extension = (char *)malloc(extension_size + 1);
            strncpy(extension, full_name + i + 1, extension_size);
            extension[extension_size] = '\0';
            self->set_extension(self, extension);
            free(extension);
            return;
        }
    }
    self->set_name(self, full_name);
}


void private_dtw_set_dir(struct DtwPath *self, const char *path){
    if(strcmp(path, "") == 0){
        return;
    }
    self->dir_exists = true;
    int path_size = strlen(path);
    self->dir = (char *)realloc(self->dir, path_size+1);
    strcpy(self->dir, path);
    self->dir[path_size] = '\0';
}

void private_dtw_set_path(struct DtwPath *self, const char *target_path) {
    self->dir_exists = false;
    self->name_exists = false;
    self->extension_exists = false;
    
    int path_size = strlen(target_path);
  
    for(int i = path_size - 1; i >= 0; i--){
        if(target_path[i] == '/' || target_path[i] == '\\'){
            
            char *path = (char *)malloc(i + 1);
            strncpy(path, target_path, i);
            path[i] = '\0';
            self->set_dir(self, path);
            free(path);

            char *full_name = (char *)malloc(path_size - i);
            strcpy(full_name, target_path + i + 1);
            full_name[path_size - i - 1] = '\0';
            self->set_full_name(self, full_name);
            free(full_name);
            return;
        }
    }

    self->set_full_name(self, target_path);
}

void private_dtw_add_start_dir(struct DtwPath *self, const char *start_dir){

    char *dir = self->get_dir(self);
    //concat the path, with start_dir at beguining
    if(dir != NULL){
        char *path = dtw_concat_path(start_dir, dir);
        self->set_dir(self, path);
        free(path);
        free(dir);
    }
}

void private_dtw_add_end_dir(struct DtwPath *self, const char *end_dir){
    char *dir = self->get_dir(self);
    //concat the path, with start_dir at beguining
    if(dir != NULL){
        char *path = dtw_concat_path(dir, end_dir);
        self->set_dir(self, path);
        free(path);
        free(dir);
    }
}

  

void private_dtw_represent_path(struct DtwPath *self){
    char  *path = self->get_path(self);
    char *full_name = self->get_full_name(self);
    char *dir = self->get_dir(self);
    char *name = self->get_name(self);
    char *extension = self->get_extension(self);
    bool changed = self->changed(self);
    printf("First Path: %s\n", self->original_path ? self->original_path : "NULL");
    printf("Path: %s\n", path  ? path : "NULL");
    printf("Path Changed: %s\n", changed ? "true" : "false");
    printf("Dir: %s\n", dir ? dir : "NULL");
    printf("Full Name: %s\n", full_name ? full_name : "NULL");
    printf("Name: %s\n", name ? name : "NULL");
    printf("Extension: %s\n", extension ? extension : "NULL");

    free(dir);
    free(name);
    free(extension);
    free(path);
    free(full_name);
    
}



void private_dtw_destructor_path(struct DtwPath *self) {
    free(self->original_path);
    free(self->dir);
    free(self->name);
    free(self->extension);
    free(self);
}


struct DtwTransactionReport{
    struct DtwStringArray *write;
    struct DtwStringArray *modify;
    struct DtwStringArray *remove;
    void (*represent)(struct DtwTransactionReport *report);
    void (*free_transaction)(struct DtwTransactionReport *report);
};

struct DtwTransactionReport * dtw_constructor_transaction_report();
void  private_dtw_represent_transaction(struct DtwTransactionReport *report);
void  private_dtw_free_transaction(struct DtwTransactionReport *report);

struct DtwStringArray * dtw_constructor_string_array(){
    struct DtwStringArray *self = (struct DtwStringArray*)malloc(sizeof(struct DtwStringArray));
    self->size = 0;

    self->strings = (char**)malloc(1);
    self->add_string = private_dtw_add_string;
    self->set_value = private_dtw_set_value;
    self->merge_string_array = private_dtw_merge_string_array;
    self->represent= private_dtw_represent_string_array;
    self->free_string_array = private_dtw_free_string_array;
    self->find_position = private_dtw_find_position;
    return self;
}

int private_dtw_find_position(struct DtwStringArray *self,const char *string){
    for(int i = 0; i < self->size; i++){
        if(strcmp(self->strings[i], string) == 0){
            return i;
        }
    }
    return -1;
}
void private_dtw_set_value(struct DtwStringArray *self,int index,const char *value){
    if(index < self->size && index >= 0){
        int size = strlen(value);
        self->strings[index] = (char*)realloc(self->strings[index], size + 1);
        self->strings[index][size] = '\0';
        strcpy(self->strings[index], value);
    }
}
// Function prototypes
void private_dtw_add_string(struct DtwStringArray *self,const char *string){
    self->size++;
    self->strings =  (char**)realloc(self->strings, self->size * sizeof(char *));
    self->strings[self->size - 1] = (char*)malloc(strlen(string) + 1);
    self->strings[self->size - 1][strlen(string)] = '\0';
    strcpy(self->strings[self->size - 1], string);
}


void private_dtw_merge_string_array(struct DtwStringArray *self, struct DtwStringArray *other){
    for(int i = 0; i < other->size; i++){
        self->add_string(self, other->strings[i]);
    }
}


void private_dtw_represent_string_array(struct DtwStringArray *self){
    for(int i = 0; i < self->size; i++){
        printf("%s\n", self->strings[i]);
    }
}
void private_dtw_free_string_array(struct DtwStringArray *self){
    for(int i = 0; i < self->size; i++){
        free(self->strings[i]);
    }
    free(self->strings);
    free(self);
}



struct DtwTreePart * dtw_tree_part_constructor(const char *path,bool load_content,bool preserve_content){
    struct DtwTreePart *self = (struct DtwTreePart *)malloc(sizeof(struct DtwTreePart));
    self->path = dtw_constructor_path(path);
    self->content_exist_in_memory = false;
    self->content_exist_in_hardware = false;
    self->is_binary = false;
    self->ignore = false;
    self->pending_action = 0;
    self->hawdware_content_sha = (char *)malloc(0);
    self->content = (unsigned char *)malloc(0);
    self->content_size = 0;
    self->hardware_content_size = 0;
    self->get_content_string_by_reference = private_dtw_get_content_string_by_reference;
    self->get_content_binary_by_reference = private_dtw_get_content_binary_by_reference;
    self->load_content_from_hardware = private_dtw_load_content_from_hardware;
    self->set_any_content = private_dtw_set_any_content;
    self->set_string_content = private_dtw_set_string_content;
    self->set_binary_content = private_dtw_set_binary_content;
    self->get_content_sha = private_dtw_get_content_sha;
    self->last_modification_time_in_string = private_dtw_last_modification_time_in_string;
    self->free_content = private_dtw_free_content;
    self->represent = private_dtw_represent_tree_part;
    self->hardware_remove = private_dtw_hardware_remove;
    self->hardware_write = private_dtw_hardware_write;
    self->hardware_modify = private_dtw_hardware_modify;
    self->hardware_commit = private_dtw_hardware_commit;
    self->free_tree_part = private_dtw_tree_part_destructor;
    self->copy_tree_part = private_dtw_copy_tree;
    if(load_content){
        
        self->load_content_from_hardware(self);
        if(preserve_content == false){
            self->free_content(self);
        }
    }
    return self;
}
char *private_dtw_get_content_string_by_reference(struct DtwTreePart *self){
    if(self->content_exist_in_memory == true){
        return (char *)self->content;
    }
    return NULL;
}

unsigned char *private_dtw_get_content_binary_by_reference(struct DtwTreePart *self){
    if(self->content_exist_in_memory == true){
        return self->content;
    }
    return NULL;
}


struct  DtwTreePart * private_dtw_copy_tree(struct DtwTreePart *self){
    char *path = self->path->get_path(self->path);

    struct DtwTreePart *new_tree_part = dtw_tree_part_constructor(path,false,false);
    free(path);

    new_tree_part->content_exist_in_memory = self->content_exist_in_memory;
    new_tree_part->content_exist_in_hardware = self->content_exist_in_hardware;
    new_tree_part->is_binary = self->is_binary;
    new_tree_part->ignore = self->ignore;
    new_tree_part->content_size = self->content_size;
    

    new_tree_part->hawdware_content_sha = (char *)malloc(strlen(self->hawdware_content_sha)+1);
    
    strcpy(new_tree_part->hawdware_content_sha,self->hawdware_content_sha);
    new_tree_part->content = (unsigned char *)malloc(self->content_size);
    
    if(new_tree_part->is_binary == false){
            new_tree_part->content[self->content_size] = '\0';    
    }
    
    memcpy(new_tree_part->content,self->content,self->content_size);

    
    return new_tree_part;
}

void private_dtw_set_any_content(struct DtwTreePart *self,unsigned char *content,int content_size,bool is_binary){

    self->free_content(self);
    self->content_exist_in_memory = true;
    self->is_binary = is_binary;
    self->content = (unsigned char *)realloc(self->content,content_size+2);
    memcpy(self->content,content,content_size);
    self->content_size = content_size;


}

void private_dtw_set_string_content(struct DtwTreePart *self,const char *content){
    self->set_any_content(
        self,
        (unsigned char*)content,
        strlen(content),
        false
    );
    
    self->content[self->content_size] = '\0';
}

void private_dtw_set_binary_content(struct DtwTreePart *self,unsigned char *content,int content_size){
    self->set_any_content(self,content,content_size,true);
}


char *private_dtw_get_content_sha(struct DtwTreePart *self){
    if(self->content_exist_in_memory){
        return dtw_generate_sha_from_string((char *)self->content);
    }
    return NULL;
}

char *private_dtw_last_modification_time_in_string(struct DtwTreePart *self){
    return dtw_convert_unix_time_to_string(self->last_modification_time);
}



void private_dtw_represent_tree_part(struct DtwTreePart *self){
    char *path = self->path->get_path(self->path);
    printf("------------------------------------------------------------\n");
    self->path->represent(self->path);
    printf("Content Exist in Memory: %s\n",self->content_exist_in_memory ? "true" : "false");
    printf("Ignore: %s\n",self->ignore ? "true" : "false");
    
    if(self->content_exist_in_memory == true || self->content_exist_in_hardware == true){
        
        char *last_moditication_in_string = self->last_modification_time_in_string(self);

        printf("Content Exist In Hardware: %s\n",self->content_exist_in_hardware ? "true" : "false");
        printf("Is Binary: %s\n",self->is_binary ? "true" : "false");
   
        
        printf("Content Size: %li\n",self->content_size);
        if(self->content_exist_in_hardware == true){
            printf("Last Modification Time in Unix: %li\n",self->last_modification_time);
            printf("Last Modification Time: %s\n",last_moditication_in_string);
            printf("Hardware SHA: %s\n",self->hawdware_content_sha);
        }

        if(self->content_exist_in_memory == true){
            char *content_sha = self->get_content_sha(self);
            printf("Content SHA:  %s\n",content_sha);
            printf ("Content: %s\n",self->content);
            free(content_sha);
        }
        
        free(last_moditication_in_string);
    }
    const char *action = private_dtw_convert_action_to_string(self->pending_action);
    printf("Pending Action: %s\n",action);
    free(path);

}


void private_dtw_free_content(struct DtwTreePart *self){
    self->content_exist_in_memory = false;
    self->content = (unsigned char *)realloc(self->content,0);
}
void private_dtw_tree_part_destructor(struct DtwTreePart *self){
    self->path->free_path(self->path);
    free(self->hawdware_content_sha);
    free(self->content);
    free(self);
}






void private_dtw_load_content_from_hardware(struct DtwTreePart *self){
    int size;
    bool is_binary;
    char *path = self->path->get_path(self->path);
    if(dtw_entity_type(path) != DTW_FILE_TYPE){
        free(path);
        return;
    }
    self->content = dtw_load_any_content(path,&size,&is_binary);
    self->content_exist_in_memory = true;
    self->is_binary = is_binary;
    self->content_size = size;
    self->hardware_content_size = size;
    self->last_modification_time = dtw_get_file_last_motification_in_unix(path);
    self->content_exist_in_hardware = true;
    free(self->hawdware_content_sha);
    self->hawdware_content_sha = dtw_generate_sha_from_string((const char*)self->content);
    free(path);
    
}



bool private_dtw_hardware_remove(struct DtwTreePart *self,bool set_as_action){
     if(self->ignore == true){
        return false;
     }
     if(set_as_action){
        self->pending_action = DTW_REMOVE;
        return false;
     }

    char *path = self->path->get_path(self->path);

    dtw_remove_any(path);
    
    free(path);
    self->content_exist_in_hardware = false;
    return true;
}

bool private_dtw_hardware_write(struct DtwTreePart *self,bool set_as_action){
    if(self->ignore == true){
        return false;
    }
    if(set_as_action){
        self->pending_action = DTW_WRITE;
        return false;
    }   
    //means that the content not exist in memory
    if(self->content_exist_in_memory == false){
        char *path = self->path->get_path(self->path);
        char *dir = self->path->get_dir(self->path);
        int entity_type = dtw_entity_type(path);
       
        if(entity_type== DTW_NOT_FOUND && dir!= NULL){
            dtw_create_dir_recursively(dir);
        
        }
        if(path!=NULL){
            free(path);
        }
        if(dir!=NULL){
            free(dir);
        }

        return true;
    }
    char *path = self->path->get_path(self->path);

    dtw_write_any_content(path,self->content,self->content_size);
    free(self->hawdware_content_sha);
    self->hawdware_content_sha = dtw_generate_sha_from_string((const char  *)self->content);
    self->content_exist_in_hardware = true;
    int now = time(NULL);
    self->last_modification_time = now;

    free(path);
    return true;
  
}

bool private_dtw_hardware_modify(struct DtwTreePart *self,bool set_as_action){
    if(self->ignore == true){
        return false;
    }
    if(set_as_action){
        self->pending_action = DTW_MODIFY;
        return false;
    }
    bool changed_path = self->path->changed(self->path);

    
    if(changed_path == true && self->content_exist_in_memory == false){
        char *old_path = self->path->original_path;
        char *new_path = self->path->get_path(self->path);
        dtw_move_any(old_path,new_path,true);
        free(new_path);
        return true;
    }
    bool write = false;

    if(changed_path == true && self->content_exist_in_memory == true ){
        char *old_path = self->path->original_path;
        dtw_remove_any(old_path);
        write = true;
    }

    if(changed_path== false && self->content_exist_in_memory == true ){
    
        if(self->content_exist_in_hardware == true){
            char *hardware_sha = self->hawdware_content_sha;
            char *memory_sha = self->get_content_sha(self);
            if(strcmp(hardware_sha,memory_sha) != 0){
                write = true;
            }
        }
        else{
            write = true;
        }
    }

    if(write){
        char *path = self->path->get_path(self->path);
        dtw_write_any_content(
            path,
            self->content,
            self->content_size
        );
        free(self->hawdware_content_sha);
        self->hawdware_content_sha = dtw_generate_sha_from_string((const char *)self->content);
        self->content_exist_in_hardware = true;
        int now = time(NULL);
        self->last_modification_time = now;

        free(path);
        return true;
    }
    return false;
}
bool private_dtw_hardware_commit(struct DtwTreePart *self){
    if(self->ignore == true){
        return false;
    }
    if(self->pending_action == DTW_REMOVE){
        return self->hardware_remove(self,DTW_EXECUTE_NOW);
    }
    if(self->pending_action == DTW_WRITE){
        return self->hardware_write(self,DTW_EXECUTE_NOW);
    }
    if(self->pending_action == DTW_MODIFY){
        return self->hardware_modify(self,DTW_EXECUTE_NOW);
    }
    return false;
}



struct  DtwTree * dtw_tree_constructor(){

    struct DtwTree *self = (struct DtwTree*)malloc(sizeof(struct DtwTree));
    self->size = 0;
    self->tree_parts = (struct DtwTreePart**)malloc(1);
    self->add_tree_part_by_copy = private_dtw_add_tree_part_copy;
    self->get_sub_tree = private_dtw_get_sub_tree;
    self->add_tree_part_by_reference = private_dtw_add_tree_part_reference;
    self->free_tree = private_dtw_free_tree;
    self->represent = private_dtw_represent_tree;
    self->add_tree_parts_from_string_array = private_dtw_add_tree_parts_from_string_array;
    self->add_tree_from_hardware = private_dtw_add_tree_from_hardware;

    self->map = private_dtw_map;
    self->filter = private_dtw_filter;

    self->find_part_by_function = private_dtw_find_by_function;
    self->find_part_by_name  = private_dtw_find_tree_part_by_name;
    self->find_part_by_path = private_dtw_find_tree_part_by_path;
    self->report = private_dtw_create_report;
    //
    self->insecure_hardware_remove_tree = private_insecure_dtw_hardware_remove_tree;
    self->insecure_hardware_write_tree = private_insecure_dtw_hardware_write_tree;
    self->hardware_commit_tree = private_dtw_hardware_commit_tree;
    return self;
}


struct DtwTree *private_dtw_get_sub_tree(struct DtwTree *self,const char *path,bool copy_content){
    struct DtwTree *sub_tree = dtw_tree_constructor();
    for(int i = 0; i < self->size; i++){
        struct DtwTreePart *tree_part = self->tree_parts[i];
        char *current_path = tree_part->path->get_path(tree_part->path);
        if(dtw_starts_with(current_path,path)){
            if(copy_content){
                sub_tree->add_tree_part_by_copy(sub_tree,tree_part->copy_tree_part(tree_part));
            }
            else{
                sub_tree->add_tree_part_by_reference(sub_tree,tree_part);

            }
        }
        free(current_path);
    }
    return sub_tree;
}


void private_dtw_add_tree_part_copy(struct DtwTree *self, struct DtwTreePart *tree_part){
    self->size++;
    self->tree_parts =  (struct DtwTreePart**)realloc(self->tree_parts, self->size * sizeof(struct DtwTreePart *));
    self->tree_parts[self->size - 1] = tree_part->copy_tree_part(tree_part);
       
}

struct DtwTransactionReport * private_dtw_create_report(struct DtwTree *self){
    struct DtwTransactionReport *report = dtw_constructor_transaction_report();
    for(int i = 0; i < self->size; i++){
        struct DtwTreePart *tree_part = self->tree_parts[i];
        int pending_action = tree_part->pending_action;
        char *path = tree_part->path->get_path(tree_part->path);
        if (pending_action == DTW_WRITE){

            report->write->add_string(report->write,path);
        }
        else if (pending_action == DTW_MODIFY){
            report->modify->add_string(report->modify,path);
        }
        else if (pending_action == DTW_REMOVE){
            report->remove->add_string(report->remove,path);
        }
        free(path);
    
    }
    return report;
}


void private_dtw_add_tree_part_reference(struct DtwTree *self, struct DtwTreePart *tree_part){
    self->size++;
    self->tree_parts =  (struct DtwTreePart**)realloc(self->tree_parts, self->size * sizeof(struct DtwTreePart *));
    self->tree_parts[self->size - 1] = tree_part;
}


void private_dtw_represent_tree(struct DtwTree *self){
    for(int i = 0; i < self->size; i++){
        self->tree_parts[i]->represent(self->tree_parts[i]);
    }
}

void private_dtw_add_tree_parts_from_string_array(struct DtwTree *self,struct DtwStringArray *paths,bool load_content,bool preserve_content){
    for(int i = 0; i < paths->size; i++){

        const char *current_path = paths->strings[i];
        struct DtwTreePart *tree_part = dtw_tree_part_constructor(
            current_path,
            load_content,
            preserve_content
        );
        self->add_tree_part_by_reference(self, tree_part);
    }
}


void private_dtw_add_tree_from_hardware(struct DtwTree *self,const char *path,bool load_content, bool preserve_content,bool preserve_path_start){



    struct DtwStringArray *path_array = dtw_list_all_recursively(path);
    self->add_tree_parts_from_string_array(self,path_array,load_content,preserve_content);
    path_array->free_string_array(path_array);

    if(preserve_path_start){
        return;
    }

    int size_to_remove = strlen(path);
    if(!dtw_ends_with(path,"/")){
        size_to_remove+=1;
    }

    for(int i =0; i < self->size; i++){
        struct DtwTreePart *current_part = self->tree_parts[i];
        struct DtwPath *current_path = current_part->path;
        char *current_path_string = current_path->get_path(current_path);
        //remove the size toremove from string

        memmove(
                current_path_string,
                current_path_string+size_to_remove,
                strlen(current_path_string) - size_to_remove +1
                );
        current_path->set_path(current_path,current_path_string);
        strcpy(current_path->original_path,current_path_string);
        free(current_path_string);
    }

}

void private_dtw_free_tree(struct DtwTree *self){
    for(int i = 0; i < self->size; i++){
        self->tree_parts[i]->free_tree_part(self->tree_parts[i]);
    }
    
    free(self->tree_parts);
    free(self);
}
void private_insecure_dtw_hardware_remove_tree(struct DtwTree *self){
    for(int i = 0; i < self->size; i++){
        self->tree_parts[i]->hardware_remove(self->tree_parts[i],DTW_EXECUTE_NOW);
    }
}

void private_insecure_dtw_hardware_write_tree(struct DtwTree *self){
    
    for(int i = 0; i < self->size; i++){
        struct DtwTreePart *tree_part = self->tree_parts[i];
        tree_part->hardware_write(tree_part,DTW_EXECUTE_NOW);
    }
}

void private_dtw_hardware_commit_tree(struct DtwTree *self){
    for(int i = 0; i < self->size; i++){
        self->tree_parts[i]->hardware_commit(self->tree_parts[i]);
    }
}



struct DtwTransactionReport * dtw_constructor_transaction_report(){
    struct DtwTransactionReport *new_report = (struct DtwTransactionReport *)malloc(sizeof(struct DtwTransactionReport));
    new_report->write = dtw_constructor_string_array();
    new_report->modify = dtw_constructor_string_array();
    new_report->remove = dtw_constructor_string_array();
    new_report->represent = private_dtw_represent_transaction;
    new_report->free_transaction = private_dtw_free_transaction;
    return new_report;
}

void  private_dtw_represent_transaction(struct DtwTransactionReport *report){
    printf("Write:---------------------------------------\n");
    report->write->represent(report->write);
    printf("Modify:--------------------------------------\n");
    report->modify->represent(report->modify);
    printf("Remove:--------------------------------------\n");
    report->remove->represent(report->remove);
    puts("");
}

void  private_dtw_free_transaction(struct DtwTransactionReport *report){
    report->write->free_string_array(report->write);
    report->modify->free_string_array(report->modify);
    report->remove->free_string_array(report->remove);
    free(report);
}
//
// Created by jurandi on 11-04-2023.
//
struct DtwTreePart *private_dtw_find_by_function(
        struct DtwTree *self,
        bool (*caller)(struct  DtwTreePart *part)
){
    for(int i = 0;i < self->size; i++){
        struct DtwTreePart *current = self->tree_parts[i];
        bool result = caller(current);
        if(result){
            return current;
        }
    }
    return NULL;
}

struct DtwTree *private_dtw_filter(
        struct DtwTree *self,
        bool (*caller)(struct  DtwTreePart *part)
){
    struct DtwTree *filtered_tree = dtw_tree_constructor();

    for(int i = 0;i < self->size; i++){

        struct DtwTreePart *current = self->tree_parts[i];

        bool result = caller(current);

        if(result){
            filtered_tree->add_tree_part_by_copy(filtered_tree,current);
        }
    }
    return filtered_tree;
}


struct DtwTree *private_dtw_map(
        struct DtwTree *self,
        struct DtwTreePart *(*caller)(struct  DtwTreePart *part)
){
    struct DtwTree *mapped_tree = dtw_tree_constructor();

    for(int i = 0;i < self->size; i++){
        struct DtwTreePart *current = self->tree_parts[i];
        struct DtwTreePart *copy = current->copy_tree_part(current);
        struct DtwTreePart *result = caller(copy);
        mapped_tree->add_tree_part_by_reference(mapped_tree,result);
    }
    return mapped_tree;
}


struct DtwTreePart *private_dtw_find_tree_part_by_name(struct DtwTree *self,const char *name){
    for(int i = 0;i < self->size; i++){
        struct DtwTreePart *current = self->tree_parts[i];
        struct DtwPath *current_path = current->path;
        char *current_name = current_path->get_full_name(current_path);
        if(current_name){

            if(strcmp(current_name, name) == 0){
                free(current_name);
                return current;
            }
            free(current_name);
        }

    }

    return NULL;
}

struct DtwTreePart *private_dtw_find_tree_part_by_path(struct DtwTree *self,const char *path){
    for(int i = 0;i < self->size; i++){
        struct DtwTreePart *current = self->tree_parts[i];
        struct DtwPath *current_path = current->path;
        char *current_path_string = current_path->get_path(current_path);
        if(current_path_string){
            if(strcmp(current_path_string, path) == 0){
                free(current_path_string);
                return current;
            }
            free(current_path_string);
        }

    }

    return NULL;
}