#include "imports.h"
#include "constants.h"
#include "structs/string_array.c"
#include "structs/path.c"
#include "functions/extras.c"

#include "functions/monodimension_listage_linux.c"
#include "functions/monodimension_listage_win32.c"
#include "functions/multidimension_listage.c"
#include "functions/listage_wrappers.c"
#include "functions/io.c"
