
// USE  THIS FILE ONLY FOR PRODUCTION
// This file is part of the DoTheWorld project.
// Do not edit this file, it is automatically generated.
// See the README.md file for more information.
/*
MIT License

Copyright (c) 2023 Mateus Moutinho Queiroz

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

#ifndef DO_THE_WORLD_H
#define DO_THE_WORLD_H

#ifndef cJSON__h
#include "dependencies/cJSON/cJSON.h"
#include "dependencies/cJSON/cJSON.c"
#endif //cJSON__h
#ifndef SHA_256_H
#include "dependencies/sha256/sha-256.h"
#include "dependencies/sha256/sha-256.c"
#endif  //SHA_256_H

#include "imports.h"
#include "string_array/string_array.h"

#include "base64/base64.h"
#include "randonizer/randonizer.h"
#include "extras/extras.h"
#include "string_functions/string_functions.h"
#include "io/io.h"
#include "numeral_io/numeral_io.h"
#include "listage_wrappers/listage_wrappers.h"
#include "monodimension_listage/monodimension_listage.h"
#include "multidimension_listage/multidimension_listage.h"
#include "path/path.h"
#include "tree/declarations.h"

#include "locker/declaration.h"
#include "transaction/declaration.h"
#include "resource/declaration.h"
#include "hash/hash.h"
#include "namespace/declaration.h"

#include "base64/base64.c"
#include "randonizer/randonizer.c"
#include "extras/extras.c"
#include "string_functions/string_functions.c"
#include "io/io.c"
#include "numeral_io/numeral_io.c"
#include "listage_wrappers/listage_wrappers.c"
#include "monodimension_listage/monodimension_listage_linux.c"
#include "monodimension_listage/monodimension_listage_win32.c"
#include "multidimension_listage/multidimension_listage.c"
#include "path/path.c"
#include "string_array/string_array.c"
#include "tree/definitions.h"
#include "locker/definition.h"

#include "resource/definition.h"
#include "transaction/definition.h"
#include "hash/hash.c"
#include "namespace/definition.h"

#endif //DO_THE_WORLD_H




